version: "3.9"
services:

  twitter-source:
    image: "twitter-source"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-cluster:9092
      - TWITTER_API_KEY
      - TWITTER_API_KEY_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - TWITTER_KEYWORDS
    depends_on:
      - kafka-cluster

  data-loader:
    image: "data-loader"
    ports:
    - "8888:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-cluster:9092
      - MONGODB_URI=mongodb://root:letMeIn!@mongo:27017/twitter?authSource=admin&retryWrites=true&w=majority
    depends_on:
      - kafka-cluster
      - twitter-source

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: letMeIn!
      MONGO_INITDB_DATABASE: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: letMeIn!

  kafka-ui:
    image: "provectuslabs/kafka-ui"
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-cluster:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2128

  kafka-cluster:
    image: "docker.io/bitnami/kafka"
    ports:
      - "9092:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-cluster:9092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  zookeeper:
    image: "docker.io/bitnami/zookeeper"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
