{
 "title": "Twitter2Mongo Application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Replica Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "data-loader",
   "type": "gauge",
   "description": "data-loader replicas available",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"data-loader\"}) / sum(kube_deployment_status_replicas{deployment=~\"data-loader\"}) * 100"
    }
   ]
  },
  {
   "title": "twitter-source",
   "type": "gauge",
   "description": "twitter-source replicas available",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"twitter-source\"}) / sum(kube_deployment_status_replicas{deployment=~\"twitter-source\"}) * 100"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Messages per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=~\"twitter-tweets\"}[5m])/5) by (topic)",
     "legendFormat": "Produced - {{consumergroup}} (topic: {{topic}})"
    },
    {
     "expr": "-sum(delta(kafka_consumergroup_current_offset{topic=~\"twitter-tweets\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "Consumed - {{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Messages per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"twitter-tweets\"}[1m])) by (topic)",
     "legendFormat": "Produced -{{topic}}"
    },
    {
     "expr": "-sum(rate(kafka_consumergroup_current_offset{topic=~\"twitter-tweets\"}[1m])) by (consumergroup, topic)",
     "legendFormat": "Consumed - {{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"twitter-tweets\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}